return {
    name = "about",
    args = nil,
    callback = function()
        print("cealshell() 2026 ©")
		print("------------")
		print("developed by janis")
		print("roblox: @the_h0lysandwich")
		print("discord: @_jxnis_")
		print("------------")
		print("moderated by flux studio")
		print("discord: .gg/Vpsyd59r5X")
    end,
    description = "Credits & Contacts for Cealshell.",
    manual = nil,
    signer = "cealshell",
    alias = nil,
}